# Generated by Django 2.0.9 on 2018-12-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='threshold',
            field=models.FloatField(default=0.6),
        ),
    ]
